### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by anibalsolon** [Novout/betterwrite#153]
https://github.com/Novout/betterwrite/blob/24ca6eb089cd64150347a09365d08f8ae5c2c89f/packages/better-write-languages/src/en-US/editor.ts#L392-L395

Missing translation:
```
        title: 'Summary',
        type: 'Style',
        fontSize: 'Font Size',
        fontFamily: 'Font Family',
```

**Comment by Novout** [comment]
Resolved in `v1.1.2`
