### ISSUE TITLE
Also count the number of sentences written.

### ISSUE THREAD

**Issue by marek-lach** [Novout/betterwrite#158]
On the statistics screen, it would be nice to also count **the total number of sentences** written within a document/file:

![statistics](https://github.com/Novout/betterwrite/assets/45913977/240a0ecd-517e-46ba-a00d-f0307b5774e2)

A sentence could be counted every time after a dot (full stop) mark is used **.** 

Unrelated to this a simple note on translation:

**Paragraph's** should be **Paragraphs** in English.
**Heading's** should be written as **Headings** (without the apostrophe ')

**Comment by Novout** [comment]
Implemented in `v1.3.7`. Thanks for contribution!
